default_stages: [ commit ]
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/timothycrosley/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: [ --check-only, --diff ]
        types: [ python ]
  - repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
      - id: black
        args: [ --check, --diff ]
        types: [ python ]