default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: tests/hardwares/data/
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff
        name: ruff check
        entry: uv run python -m ruff check
        language: system
        types_or: [python, pyi]
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: ruff format
        entry: uv run python -m ruff format
        language: system
        types_or: [python, pyi]
      - id: ty
        name: ty type checker
        entry: uv run python -m ty check
        language: system
        types: [python]
        pass_filenames: false
