name: Release to PyPI

on:
  push:
    tags: [ 'v*' ]

defaults:
  run:
    working-directory: ./

jobs:
  validate-git-tag:
    name: Validate the git tag
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: compare git tag with cargo metadata
        run: |
          TAG=${GITHUB_REF##*/}
          CURR_VER=$( grep version pyproject.toml | head -n 1 | awk '{print $3}' | tr -d '"' )
          if [[ "${TAG}" != "v${CURR_VER}" ]]; then
            echo "Pyproject metadata has version set to ${CURR_VER}, but got pushed tag ${TAG}."
            exit 1
          fi

  release-pypi-mac-and-windows:
    needs: validate-git-tag
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, windows-2019] 
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup
        run: make setup

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.13
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          repository_username: ${{ secrets.PYPI_USERNAME }
          repository_password: ${{ secrets.PYPI_PASSWORD }}
          build_format: "wheel"
          ignore_dev_requirements: "yes"

  release-pypi:
    needs: validate-git-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup
        run: make setup

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.13
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          repository_username: ${{ secrets.PYPI_USERNAME }
          repository_password: ${{ secrets.PYPI_PASSWORD }}
          ignore_dev_requirements: "yes"

  release-documentation:
    needs: release-pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.4

      - name: Setup
        run: make setup

      - name: Build and Publish Sphinx documentation
        run: |
          echo "Generate the new documentation"
          make build-documentation
          mv docs/build ~/build
          
          echo "Configure git"
          git config --global user.name 'Github Action'
          git config --global user.email 'fvaleye@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          
          echo "Commit the new changes in the gh-pages"
          git reset --hard HEAD
          git clean -d -fx .
          git fetch
          git checkout gh-pages
          cd ..
          cp -avr ~/build/html/.  ./documentation
          
          CURR_VER=$( grep version pyproject.toml | head -n 1 | awk '{print $3}' | tr -d '"' )          
          git status
          git add ./documentation
          git commit -m "Publish the new documentation for v${CURR_VER}"
          git push origin gh-pages